### ISSUE TITLE
自动生成generator.xml 

### ISSUE THREAD

**Issue by kitonGao** [RAOE/next1-boot#1]
generator.xml  为什么要放在class文件，通常不都是直接编译源文件就可以的吗？ 如果是放在编译文件的话，是如果找到xml文件中的相关配置的路径

**Comment by RAOE** [comment]
在代码生成这一块儿我做的并不够好，后期会对这里进行优化，我采用的思路是读取xml文件然后查询数据库并通过freemaker模版引擎产生相关的代码文件。是如果找到xml文件中的相关配置的路径？这句话是什么意思

**Comment by RAOE** [comment]
如果有更好的解决思路的话，能否告知合并代码谢谢

**Comment by kitonGao** [comment]
不好意思，最后一个没说明清楚，那你现在是如何取通过generator 生成一系列文件的。我荡下来之后，他这个文件是没有的，我自己在指定的文件中取新建了一个。可能是位置放错了。报"当前路径没有generatorCRUD.xml这个文件“ ，你可否弄一下这块。我技术没你好。有的地方还看不懂呢。。哈哈。
 还有一个地方。这个我在api模块中thymeleaf中放入了一个模板(整个页面的框架。但是会报URL错误。是哪里配置的问题吗？ 还是被某个地方拦截了..)求教!

**Comment by RAOE** [comment]
哦哦，当前路径没有generatitorCRUD这个文件这个问题已经解决了。刚刚已经把这个文件提交上去了，现在还在优化整理项目， 感谢你的持续关注

**Comment by RAOE** [comment]
@SysLog
    @ApiOperation(value = "跳转到登陆页面")
    @GetMapping("/login")
    public ModelAndView login() {
        return new ModelAndView("login");
    }
你是这样的跳转的吗

**Comment by kitonGao** [comment]
看到了， 有一些比较小的bug，主页面验证码参数错了。ajax没有data属性，后台拿不到值。希望可以集成一个前端ui  组件.

**Comment by kitonGao** [comment]
方法上面没有写 @ApiOperation ，我看你application.yml文件中 路径前缀是thymeleaf/   所以我把前端框架全部扔到到/thymeleaf/admin/...... 中了， 后台登录成功后， 后台直接就转到  “admin/index” ，  报路径找不到。

**Comment by RAOE** [comment]
.....UI 框架目前用的是bootstrap
